Fix R Windows CI: add -ldl for OpenMP dynamic loading functions
The previous fix added -lgomp for OpenMP, but libgomp.a requires
dynamic loading functions (dlsym, dlopen, dlclose, dlerror) which
are provided by the dl library on Windows POSIX toolchain.

Error was:
  undefined reference to 'dlsym'
  undefined reference to 'dlopen'
  undefined reference to 'dlerror'
  undefined reference to 'dlclose'

Fixed by adding -ldl after -lgomp in PKG_LIBS.

This is required by Rtools45 which uses the POSIX toolchain
(x86_64-w64-mingw32.static.posix) where libgomp depends on libdl.

Fixes R Windows CI linker errors for dynamic loading.