fix: replace reserved existing function stderr
This conflicts only on Windows this a funny error:
    error C2440: '<function-style-cast>': cannot convert from 'FILE *' to 'arma::colvec'